// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID               int64
	UserID           int64
	SessionTokenHash string
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
