// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    session_token_hash,
    user_agent,
    ip_address,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, session_token_hash, user_agent, ip_address, expires_at, created_at, last_seen_at
`

type CreateSessionParams struct {
	UserID           int64
	SessionTokenHash string
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE session_token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionTokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id,
    sessions.user_id,
    sessions.session_token_hash,
    sessions.user_agent,
    sessions.ip_address,
    sessions.expires_at,
    sessions.created_at,
    sessions.last_seen_at,
    users.id AS user_id,
    users.email,
    users.username,
    users.password_hash,
    users.created_at AS user_created_at,
    users.updated_at AS user_updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.session_token_hash = $1
  AND sessions.expires_at > NOW()
`

type GetSessionByTokenHashRow struct {
	ID               int64
	UserID           int64
	SessionTokenHash string
	UserAgent        pgtype.Text
	IpAddress        pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	LastSeenAt       pgtype.Timestamptz
	UserID_2         int64
	Email            string
	Username         string
	PasswordHash     string
	UserCreatedAt    pgtype.Timestamptz
	UserUpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, sessionTokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.UserID_2,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}
